-- 사원번호를 전달하면 해당 사원의 이름을 반환하는 함수 만들기

CREATE OR REPLACE FUNCTION GET_NAME(EMPNO EMPLOYEE_TBL.EMP_NO%TYPE)
RETURN VARCHAR2
IS
    EMPNAME EMPLOYEE_TBL.NAME%TYPE;
BEGIN
    SELECT NAME -- 3
      INTO EMPNAME -- 4
      FROM EMPLOYEE_TBL -- 1
     WHERE EMP_NO = EMPNO; -- 1001로 사용 (2)
    RETURN EMPNAME; -- 5
END;
-- 사원명
-- 구창민

SELECT GET_NAME(1001) AS 사원명
  FROM EMPLOYEE_TBL
 WHERE EMP_NO = 1001; -- 특정 한명 조건
 
 SELECT DISTINCT GET_NAME(1001) AS 사원명
   FROM EMPLOYEE_TBL;

SELECT GET_NAME(EMP_NO) AS 사원명
  FROM EMPLOYEE_TBL; -- 전체 사원 불러오기